import { Injectable } from "@nestjs/common";
import { AiProvider, AiProviderRequest, AiProviderResponse } from "./ai-provider.types";
import { AiResponseValidationError, parseAndValidateAiOutput } from "./ai-output-schemas";

interface OllamaProviderOptions {
  baseUrl?: string;
  model?: string;
  timeoutMs?: number;
  keepAlive?: string;
}

interface OllamaChatResponse {
  model?: string;
  message?: { content?: string };
}

export class OllamaProviderError extends Error {
  constructor(readonly code: "timeout" | "unavailable" | "http_error" | "invalid_response", readonly status?: number) {
    super(code);
    this.name = "OllamaProviderError";
  }
}

@Injectable()
export class OllamaAiProvider implements AiProvider {
  readonly providerName = "ollama";
  private readonly baseUrl: string;
  private readonly model: string;
  private readonly timeoutMs: number;
  private readonly keepAlive: string;

  constructor(options: OllamaProviderOptions = {}, private readonly fetchImpl: typeof fetch = fetch) {
    this.baseUrl = (options.baseUrl ?? process.env.OLLAMA_BASE_URL ?? "http://127.0.0.1:11434").replace(/\/$/, "");
    this.model = options.model ?? process.env.OLLAMA_MODEL ?? "qwen3:4b";
    this.timeoutMs = positiveNumber(options.timeoutMs ?? process.env.OLLAMA_TIMEOUT_MS, 45_000);
    this.keepAlive = options.keepAlive ?? process.env.OLLAMA_KEEP_ALIVE ?? "5m";
  }

  async generate<TOutput>(request: AiProviderRequest, _fallbackOutput: TOutput): Promise<AiProviderResponse<TOutput>> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), this.timeoutMs);
    try {
      const response = await this.fetchImpl(`${this.baseUrl}/api/chat`, {
        method: "POST",
        signal: controller.signal,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: this.model,
          stream: false,
          think: false,
          keep_alive: this.keepAlive,
          format: request.outputSchema,
          options: { temperature: 0.1 },
          messages: [
            { role: "system", content: request.systemInstruction },
            {
              role: "user",
              content: JSON.stringify({
                language: request.language,
                input: request.userInput,
                context: request.context,
                criteria: request.criteria,
                outputSchema: request.outputSchema
              })
            }
          ]
        })
      });
      if (!response.ok) throw new OllamaProviderError("http_error", response.status);
      const payload = (await response.json()) as OllamaChatResponse;
      const content = payload.message?.content;
      if (!content) throw new OllamaProviderError("invalid_response", response.status);

      let output: TOutput;
      try {
        output = parseAndValidateAiOutput<TOutput>(content, request.outputSchema);
      } catch (error) {
        if (error instanceof AiResponseValidationError) throw new OllamaProviderError("invalid_response", response.status);
        throw error;
      }

      return {
        output,
        modelName: payload.model ?? this.model,
        providerName: this.providerName,
        promptTemplateVersion: request.promptTemplateVersion,
        confidenceLevel: readConfidence(output),
        limitations: ["Generated by a model running on the local Ollama service."],
        createdAt: new Date().toISOString()
      };
    } catch (error) {
      if (error instanceof OllamaProviderError) throw error;
      if (error instanceof Error && error.name === "AbortError") throw new OllamaProviderError("timeout");
      throw new OllamaProviderError("unavailable");
    } finally {
      clearTimeout(timeout);
    }
  }
}

function positiveNumber(value: number | string | undefined, fallback: number) {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function readConfidence(output: unknown): "low" | "medium" | "high" {
  if (output && typeof output === "object" && "confidenceLevel" in output) {
    const value = (output as { confidenceLevel?: unknown }).confidenceLevel;
    if (value === "low" || value === "medium" || value === "high") return value;
  }
  return "medium";
}
